"""phase2_schema

Revision ID: 5e3743110c60
Revises: 
Create Date: 2026-03-05 15:11:31.129239
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e3743110c60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_programs',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('stream', sa.Enum('NATURAL', 'SOCIAL', name='streamtype'), nullable=False),
    sa.Column('cut_off_score', sa.Float(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_programs_code'), 'academic_programs', ['code'], unique=True)
    op.create_index(op.f('ix_academic_programs_department'), 'academic_programs', ['department'], unique=False)
    op.create_index(op.f('ix_academic_programs_stream'), 'academic_programs', ['stream'], unique=False)
    op.create_table('system_audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_audit_logs_resource_id'), 'system_audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_system_audit_logs_resource_type'), 'system_audit_logs', ['resource_type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'REGISTRAR_OFFICER', 'ADMIN', 'SYSTEM', 'AGENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('undergraduate_applications',
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('sponsorship_type', sa.Enum('GOVERNMENT', 'SELF_SPONSORED', name='sponsorshiptype'), nullable=False),
    sa.Column('stream', sa.Enum('NATURAL', 'SOCIAL', name='streamtype'), nullable=False),
    sa.Column('program_choice_1_id', sa.UUID(), nullable=True),
    sa.Column('program_choice_2_id', sa.UUID(), nullable=True),
    sa.Column('program_choice_3_id', sa.UUID(), nullable=True),
    sa.Column('admission_term', sa.String(length=50), nullable=False),
    sa.Column('current_status', sa.Enum('DRAFT', 'SUBMITTED', 'PAYMENT_PENDING', 'PAYMENT_VERIFIED', 'UNDER_VERIFICATION', 'AI_PRE_SCREENING', 'PENDING_REVIEW', 'DECIDED', name='applicationstatus'), nullable=False),
    sa.Column('final_decision', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_choice_1_id'], ['academic_programs.id'], ),
    sa.ForeignKeyConstraint(['program_choice_2_id'], ['academic_programs.id'], ),
    sa.ForeignKeyConstraint(['program_choice_3_id'], ['academic_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id', 'admission_term', name='uq_one_app_per_term')
    )
    op.create_index(op.f('ix_undergraduate_applications_admission_term'), 'undergraduate_applications', ['admission_term'], unique=False)
    op.create_index(op.f('ix_undergraduate_applications_applicant_id'), 'undergraduate_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_undergraduate_applications_current_status'), 'undergraduate_applications', ['current_status'], unique=False)
    op.create_table('ai_evaluations',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('agent_version', sa.String(length=100), nullable=False),
    sa.Column('recommended_decision', sa.Enum('RECOMMEND_ADMIT', 'RECOMMEND_REJECT', 'RECOMMEND_WAITLIST', 'FLAG_FOR_REVIEW', 'ADMIT', 'REJECT', 'WAITLIST', name='decisiontype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('summary_reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['undergraduate_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_evaluations_application_id'), 'ai_evaluations', ['application_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('TRANSCRIPT', 'GRADE_12_CERTIFICATE', 'ID_CARD', 'CERTIFICATE', 'RECOMMENDATION_LETTER', 'STATEMENT_OF_PURPOSE', name='documenttype'), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['undergraduate_applications.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_documents_verification_status'), 'application_documents', ['verification_status'], unique=False)
    op.create_table('application_status_history',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('DRAFT', 'SUBMITTED', 'PAYMENT_PENDING', 'PAYMENT_VERIFIED', 'UNDER_VERIFICATION', 'AI_PRE_SCREENING', 'PENDING_REVIEW', 'DECIDED', name='applicationstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'SUBMITTED', 'PAYMENT_PENDING', 'PAYMENT_VERIFIED', 'UNDER_VERIFICATION', 'AI_PRE_SCREENING', 'PENDING_REVIEW', 'DECIDED', name='applicationstatus'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['undergraduate_applications.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_table('registrar_decisions',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('human_decision', sa.Enum('RECOMMEND_ADMIT', 'RECOMMEND_REJECT', 'RECOMMEND_WAITLIST', 'FLAG_FOR_REVIEW', 'ADMIT', 'REJECT', 'WAITLIST', name='decisiontype'), nullable=False),
    sa.Column('justification_remarks', sa.Text(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['undergraduate_applications.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_registrar_decisions_reviewer_id'), 'registrar_decisions', ['reviewer_id'], unique=False)
    op.create_table('ai_execution_traces',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('reasoning_log', sa.Text(), nullable=False),
    sa.Column('rag_references', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['ai_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_execution_traces_evaluation_id'), 'ai_execution_traces', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_execution_traces_evaluation_id'), table_name='ai_execution_traces')
    op.drop_table('ai_execution_traces')
    op.drop_index(op.f('ix_registrar_decisions_reviewer_id'), table_name='registrar_decisions')
    op.drop_table('registrar_decisions')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_application_documents_verification_status'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_ai_evaluations_application_id'), table_name='ai_evaluations')
    op.drop_table('ai_evaluations')
    op.drop_index(op.f('ix_undergraduate_applications_current_status'), table_name='undergraduate_applications')
    op.drop_index(op.f('ix_undergraduate_applications_applicant_id'), table_name='undergraduate_applications')
    op.drop_index(op.f('ix_undergraduate_applications_admission_term'), table_name='undergraduate_applications')
    op.drop_table('undergraduate_applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_audit_logs_resource_type'), table_name='system_audit_logs')
    op.drop_index(op.f('ix_system_audit_logs_resource_id'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    op.drop_index(op.f('ix_academic_programs_stream'), table_name='academic_programs')
    op.drop_index(op.f('ix_academic_programs_department'), table_name='academic_programs')
    op.drop_index(op.f('ix_academic_programs_code'), table_name='academic_programs')
    op.drop_table('academic_programs')
    # ### end Alembic commands ###
