"""create_moe_table

Revision ID: e3b0f4801228
Revises: 34dfb3896be5
Create Date: 2026-03-05 16:46:02.015919
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3b0f4801228'
down_revision: Union[str, None] = '34dfb3896be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moe_student_records',
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('stream', postgresql.ENUM('NATURAL', 'SOCIAL', name='streamtype', create_type=False), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='{"Physics": 85, "Math": 92, "English": 78, ...}'),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moe_student_records_admission_number'), 'moe_student_records', ['admission_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moe_student_records_admission_number'), table_name='moe_student_records')
    op.drop_table('moe_student_records')
    # ### end Alembic commands ###
